spring.application.name=buildexpenseanalyzer

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.api-key=${GEMINI_API_KEY}
spring.ai.openai.chat.options.model=openrouter/free

server.port=${PORT:8080}